use projetoIntegradorTelemedicina;

INSERT INTO Exame (diagnosticoExame, statusExame, dataExame, localExame, descricaoExame) VALUES 
('Hipertensão Arterial', 'Concluído', '2024-08-15', 'Clínica São João', 'Exame para avaliação da pressão arterial e monitoramento de hipertensão.'),
('Diabetes Tipo 2', 'Pendente', '2024-08-16', 'Clínica Santa Maria', 'Exame de glicemia para controle e monitoramento de diabetes tipo 2.'),
('Colesterol Alto', 'Em andamento', '2024-08-17', 'Clínica do Coração', 'Avaliação de níveis de colesterol e triglicerídeos no sangue.'),
('Anemia Ferropriva', 'Concluído', '2024-08-18', 'Clínica Vida Saudável', 'Exame de hemoglobina para diagnóstico de anemia ferropriva.'),
('Insuficiência Renal', 'Pendente', '2024-08-19', 'Clínica Renal', 'Exame de creatinina e ureia para avaliação da função renal.'),
('Artrite Reumatoide', 'Em andamento', '2024-08-20', 'Clínica de Ortopedia', 'Exame de sangue para detectar marcadores de artrite reumatoide.'),
('Asma', 'Concluído', '2024-08-21', 'Clínica Respiratória', 'Exame de função pulmonar para diagnóstico de asma.'),
('Tuberculose', 'Pendente', '2024-08-22', 'Clínica de Infectologia', 'Teste tuberculínico para detecção de tuberculose.'),
('Doença Celíaca', 'Em andamento', '2024-08-23', 'Clínica Gastro', 'Exame de anticorpos para diagnóstico de doença celíaca.'),
('Câncer de Mama', 'Concluído', '2024-08-24', 'Clínica Oncológica', 'Mamografia para rastreamento e diagnóstico de câncer de mama.'),
('Hipoglicemia', 'Concluído', '2024-08-25', 'Clínica de Endocrinologia', 'Exame para avaliação de níveis de glicose no sangue.'),
('Osteoporose', 'Pendente', '2024-08-26', 'Clínica de Ortopedia', 'Densitometria óssea para diagnóstico de osteoporose.'),
('Gastrite Crônica', 'Em andamento', '2024-08-27', 'Clínica Gastroenterológica', 'Endoscopia para avaliação de gastrite crônica.'),
('Hepatite B', 'Concluído', '2024-08-28', 'Clínica de Hepatologia', 'Exame de sangue para diagnóstico de hepatite B.'),
('Psoríase', 'Pendente', '2024-08-29', 'Clínica Dermatológica', 'Exame de pele para diagnóstico e avaliação de psoríase.'),
('Alergia Alimentar', 'Em andamento', '2024-08-30', 'Clínica de Alergias', 'Testes alérgicos para identificar alergias alimentares.'),
('Doença Pulmonar Obstrutiva Crônica', 'Concluído', '2024-08-31', 'Clínica Respiratória', 'Exame de função pulmonar para diagnóstico de DPOC.'),
('Glaucoma', 'Pendente', '2024-09-01', 'Clínica Oftalmológica', 'Exame de pressão ocular para rastreamento de glaucoma.'),
('Sindrome de Sjögren', 'Em andamento', '2024-09-02', 'Clínica de Reumatologia', 'Exame de anticorpos e avaliação clínica para síndrome de Sjögren.'),
('Síndrome Metabólica', 'Concluído', '2024-09-03', 'Clínica de Cardiologia', 'Exame de perfil lipídico e avaliação de fatores de risco para síndrome metabólica.'),
('Hipoglicemia', 'Concluído', '2024-08-25', 'Clínica de Endocrinologia', 'Exame para avaliação de níveis de glicose no sangue.'),
('Osteoporose', 'Pendente', '2024-08-26', 'Clínica de Ortopedia', 'Densitometria óssea para diagnóstico de osteoporose.'),
('Gastrite Crônica', 'Em andamento', '2024-08-27', 'Clínica Gastroenterológica', 'Endoscopia para avaliação de gastrite crônica.'),
('Hepatite B', 'Concluído', '2024-08-28', 'Clínica de Hepatologia', 'Exame de sangue para diagnóstico de hepatite B.'),
('Psoríase', 'Pendente', '2024-08-29', 'Clínica Dermatológica', 'Exame de pele para diagnóstico e avaliação de psoríase.'),
('Alergia Alimentar', 'Em andamento', '2024-08-30', 'Clínica de Alergias', 'Testes alérgicos para identificar alergias alimentares.'),
('Doença Pulmonar Obstrutiva Crônica', 'Concluído', '2024-08-31', 'Clínica Respiratória', 'Exame de função pulmonar para diagnóstico de DPOC.'),
('Glaucoma', 'Pendente', '2024-09-01', 'Clínica Oftalmológica', 'Exame de pressão ocular para rastreamento de glaucoma.'),
('Sindrome de Sjögren', 'Em andamento', '2024-09-02', 'Clínica de Reumatologia', 'Exame de anticorpos e avaliação clínica para síndrome de Sjögren.'),
('Síndrome Metabólica', 'Concluído', '2024-09-03', 'Clínica de Cardiologia', 'Exame de perfil lipídico e avaliação de fatores de risco para síndrome metabólica.'),
('Hipotireoidismo', 'Concluído', '2024-09-14', 'Clínica Endocrinológica', 'Exame de sangue para avaliação da função tireoidiana e diagnóstico de hipotireoidismo.'),
('Bradicardia', 'Pendente', '2024-09-15', 'Clínica Cardiológica', 'Eletrocardiograma para diagnóstico de bradicardia.'),
('Cálculo Renal', 'Em andamento', '2024-09-16', 'Clínica Urológica', 'Ultrassonografia para detecção de cálculo renal.'),
('Esclerose Múltipla', 'Concluído', '2024-09-17', 'Clínica Neurológica', 'Ressonância magnética para diagnóstico de esclerose múltipla.'),
('Síndrome do Ovário Policístico', 'Pendente', '2024-09-18', 'Clínica Ginecológica', 'Ultrassonografia pélvica e exames hormonais para diagnóstico de SOP.'),
('Acidente Vascular Cerebral (AVC)', 'Em andamento', '2024-09-19', 'Clínica Neurológica', 'Tomografia computadorizada para avaliação de AVC.'),
('Tinnitus', 'Concluído', '2024-09-20', 'Clínica Otorrinolaringológica', 'Exame auditivo e avaliação clínica para diagnóstico de tinnitus.'),
('Hiperuricemia', 'Pendente', '2024-09-21', 'Clínica Rheumatológica', 'Exame de sangue para avaliação dos níveis de ácido úrico e diagnóstico de hiperuricemia.'),
('Fibrose Hepática', 'Em andamento', '2024-09-22', 'Clínica Hepatológica', 'Elastografia hepática para diagnóstico de fibrose hepática.'),
('Câncer de Colo do Útero', 'Concluído', '2024-09-23', 'Clínica Ginecológica', 'Papanicolau para rastreamento e diagnóstico de câncer de colo do útero.'),
('Infecção por HPV', 'Concluído', '2024-09-24', 'Clínica Ginecológica', 'Teste de HPV para detecção de infecção pelo vírus do papiloma humano.'),
('Miopia', 'Pendente', '2024-09-25', 'Clínica Oftalmológica', 'Exame de refração ocular para diagnóstico de miopia.'),
('Hipertensão Pulmonar', 'Em andamento', '2024-09-26', 'Clínica Cardiológica', 'Ecocardiograma para avaliação de hipertensão pulmonar.'),
('Hérnia Abdominal', 'Concluído', '2024-09-27', 'Clínica Cirúrgica', 'Ultrassonografia para diagnóstico de hérnia abdominal.'),
('Neuropatia Periférica', 'Pendente', '2024-09-28', 'Clínica Neurológica', 'Exame de condução nervosa para diagnóstico de neuropatia periférica.'),
('Sindrome de Apneia do Sono', 'Em andamento', '2024-09-29', 'Clínica do Sono', 'Polissonografia para diagnóstico de apneia do sono.'),
('Câncer de Pulmão', 'Concluído', '2024-09-30', 'Clínica Oncológica', 'Tomografia computadorizada para rastreamento de câncer de pulmão.'),
('Espondilite Anquilosante', 'Pendente', '2024-10-01', 'Clínica Rheumatológica', 'Ressonância magnética para avaliação de espondilite anquilosante.'),
('Dermatite Atópica', 'Em andamento', '2024-10-02', 'Clínica Dermatológica', 'Avaliação clínica e teste de alergia para diagnóstico de dermatite atópica.'),
('Leucemia', 'Concluído', '2024-10-03', 'Clínica Hematológica', 'Exame de sangue completo e mielograma para diagnóstico de leucemia.');

select * from Exame;
