use projetoIntegradorTelemedicina;

INSERT INTO Exame (diagnosticoExame, statusExame, dataExame, localExame, descricaoExame, valorExame) VALUES 
('Hipertensão Arterial', 'Concluído', '2024-08-15', 'Clínica São João', 'Exame para avaliação da pressão arterial e monitoramento de hipertensão.', 250.00),
('Diabetes Tipo 2', 'Pendente', '2024-08-16', 'Clínica Santa Maria', 'Exame de glicemia para controle e monitoramento de diabetes tipo 2.', 250.00),
('Colesterol Alto', 'Em andamento', '2024-08-17', 'Clínica do Coração', 'Avaliação de níveis de colesterol e triglicerídeos no sangue.', 250.00),
('Anemia Ferropriva', 'Concluído', '2024-08-18', 'Clínica Vida Saudável', 'Exame de hemoglobina para diagnóstico de anemia ferropriva.', 250.00),
('Insuficiência Renal', 'Pendente', '2024-08-19', 'Clínica Renal', 'Exame de creatinina e ureia para avaliação da função renal.', 250.00),
('Artrite Reumatoide', 'Em andamento', '2024-08-20', 'Clínica de Ortopedia', 'Exame de sangue para detectar marcadores de artrite reumatoide.', 250.00),
('Asma', 'Concluído', '2024-08-21', 'Clínica Respiratória', 'Exame de função pulmonar para diagnóstico de asma.', 250.00),
('Tuberculose', 'Pendente', '2024-08-22', 'Clínica de Infectologia', 'Teste tuberculínico para detecção de tuberculose.', 250.00),
('Doença Celíaca', 'Em andamento', '2024-08-23', 'Clínica Gastro', 'Exame de anticorpos para diagnóstico de doença celíaca.', 250.00),
('Câncer de Mama', 'Concluído', '2024-08-24', 'Clínica Oncológica', 'Mamografia para rastreamento e diagnóstico de câncer de mama.', 250.00),
('Hipoglicemia', 'Concluído', '2024-08-25', 'Clínica de Endocrinologia', 'Exame para avaliação de níveis de glicose no sangue.', 250.00),
('Osteoporose', 'Pendente', '2024-08-26', 'Clínica de Ortopedia', 'Densitometria óssea para diagnóstico de osteoporose.', 250.00),
('Gastrite Crônica', 'Em andamento', '2024-08-27', 'Clínica Gastroenterológica', 'Endoscopia para avaliação de gastrite crônica.', 250.00),
('Hepatite B', 'Concluído', '2024-08-28', 'Clínica de Hepatologia', 'Exame de sangue para diagnóstico de hepatite B.', 250.00),
('Psoríase', 'Pendente', '2024-08-29', 'Clínica Dermatológica', 'Exame de pele para diagnóstico e avaliação de psoríase.', 250.00),
('Alergia Alimentar', 'Em andamento', '2024-08-30', 'Clínica de Alergias', 'Testes alérgicos para identificar alergias alimentares.', 250.00),
('Doença Pulmonar Obstrutiva Crônica', 'Concluído', '2024-08-31', 'Clínica Respiratória', 'Exame de função pulmonar para diagnóstico de DPOC.', 250.00),
('Glaucoma', 'Pendente', '2024-09-01', 'Clínica Oftalmológica', 'Exame de pressão ocular para rastreamento de glaucoma.', 250.00),
('Sindrome de Sjögren', 'Em andamento', '2024-09-02', 'Clínica de Reumatologia', 'Exame de anticorpos e avaliação clínica para síndrome de Sjögren.', 250.00),
('Síndrome Metabólica', 'Concluído', '2024-09-03', 'Clínica de Cardiologia', 'Exame de perfil lipídico e avaliação de fatores de risco para síndrome metabólica.', 250.00),
('Hipoglicemia', 'Concluído', '2024-08-25', 'Clínica de Endocrinologia', 'Exame para avaliação de níveis de glicose no sangue.', 250.00),
('Osteoporose', 'Pendente', '2024-08-26', 'Clínica de Ortopedia', 'Densitometria óssea para diagnóstico de osteoporose.', 250.00),
('Gastrite Crônica', 'Em andamento', '2024-08-27', 'Clínica Gastroenterológica', 'Endoscopia para avaliação de gastrite crônica.', 250.00),
('Hepatite B', 'Concluído', '2024-08-28', 'Clínica de Hepatologia', 'Exame de sangue para diagnóstico de hepatite B.', 250.00),
('Psoríase', 'Pendente', '2024-08-29', 'Clínica Dermatológica', 'Exame de pele para diagnóstico e avaliação de psoríase.', 250.00),
('Alergia Alimentar', 'Em andamento', '2024-08-30', 'Clínica de Alergias', 'Testes alérgicos para identificar alergias alimentares.', 250.00),
('Doença Pulmonar Obstrutiva Crônica', 'Concluído', '2024-08-31', 'Clínica Respiratória', 'Exame de função pulmonar para diagnóstico de DPOC.', 250.00),
('Glaucoma', 'Pendente', '2024-09-01', 'Clínica Oftalmológica', 'Exame de pressão ocular para rastreamento de glaucoma.', 250.00),
('Sindrome de Sjögren', 'Em andamento', '2024-09-02', 'Clínica de Reumatologia', 'Exame de anticorpos e avaliação clínica para síndrome de Sjögren.', 250.00),
('Síndrome Metabólica', 'Concluído', '2024-09-03', 'Clínica de Cardiologia', 'Exame de perfil lipídico e avaliação de fatores de risco para síndrome metabólica.', 250.00),
('Hipotireoidismo', 'Concluído', '2024-09-14', 'Clínica Endocrinológica', 'Exame de sangue para avaliação da função tireoidiana e diagnóstico de hipotireoidismo.', 250.00),
('Bradicardia', 'Pendente', '2024-09-15', 'Clínica Cardiológica', 'Eletrocardiograma para diagnóstico de bradicardia.', 250.00),
('Cálculo Renal', 'Em andamento', '2024-09-16', 'Clínica Urológica', 'Ultrassonografia para detecção de cálculo renal.', 250.00),
('Esclerose Múltipla', 'Concluído', '2024-09-17', 'Clínica Neurológica', 'Ressonância magnética para diagnóstico de esclerose múltipla.', 250.00),
('Síndrome do Ovário Policístico', 'Pendente', '2024-09-18', 'Clínica Ginecológica', 'Ultrassonografia pélvica e exames hormonais para diagnóstico de SOP.', 250.00),
('Acidente Vascular Cerebral (AVC)', 'Em andamento', '2024-09-19', 'Clínica Neurológica', 'Tomografia computadorizada para avaliação de AVC.', 250.00),
('Tinnitus', 'Concluído', '2024-09-20', 'Clínica Otorrinolaringológica', 'Exame auditivo e avaliação clínica para diagnóstico de tinnitus.', 250.00),
('Hiperuricemia', 'Pendente', '2024-09-21', 'Clínica Rheumatológica', 'Exame de sangue para avaliação dos níveis de ácido úrico e diagnóstico de hiperuricemia.', 250.00),
('Fibrose Hepática', 'Em andamento', '2024-09-22', 'Clínica Hepatológica', 'Elastografia hepática para diagnóstico de fibrose hepática.', 250.00),
('Câncer de Colo do Útero', 'Concluído', '2024-09-23', 'Clínica Ginecológica', 'Papanicolau para rastreamento e diagnóstico de câncer de colo do útero.', 250.00),
('Infecção por HPV', 'Concluído', '2024-09-24', 'Clínica Ginecológica', 'Teste de HPV para detecção de infecção pelo vírus do papiloma humano.', 250.00),
('Miopia', 'Pendente', '2024-09-25', 'Clínica Oftalmológica', 'Exame de refração ocular para diagnóstico de miopia.', 250.00),
('Hipertensão Pulmonar', 'Em andamento', '2024-09-26', 'Clínica Cardiológica', 'Ecocardiograma para avaliação de hipertensão pulmonar.', 250.00),
('Hérnia Abdominal', 'Concluído', '2024-09-27', 'Clínica Cirúrgica', 'Ultrassonografia para diagnóstico de hérnia abdominal.', 250.00),
('Neuropatia Periférica', 'Pendente', '2024-09-28', 'Clínica Neurológica', 'Exame de condução nervosa para diagnóstico de neuropatia periférica.', 250.00),
('Sindrome de Apneia do Sono', 'Em andamento', '2024-09-29', 'Clínica do Sono', 'Polissonografia para diagnóstico de apneia do sono.', 250.00),
('Câncer de Pulmão', 'Concluído', '2024-09-30', 'Clínica Oncológica', 'Tomografia computadorizada para rastreamento de câncer de pulmão.', 250.00),
('Espondilite Anquilosante', 'Pendente', '2024-10-01', 'Clínica Rheumatológica', 'Ressonância magnética para avaliação de espondilite anquilosante.', 250.00),
('Dermatite Atópica', 'Em andamento', '2024-10-02', 'Clínica Dermatológica', 'Avaliação clínica e teste de alergia para diagnóstico de dermatite atópica.', 250.00),
('Leucemia', 'Concluído', '2024-10-03', 'Clínica Hematológica', 'Exame de sangue completo e mielograma para diagnóstico de leucemia.', 250.90);

select * from Exame;
