INSERT INTO Prescricao (assinatura, medicamento, ID_PACIENTE, ID_MEDICO) VALUES
('Dr. Ana Souza', 'Paracetamol 500mg - 30 comprimidos'),
('Dr. João Silva', 'Ibuprofeno 400mg - 20 cápsulas'),
('Dra. Maria Oliveira', 'Amoxicilina 500mg - 15 cápsulas'),
('Dr. Carlos Almeida', 'Dipirona 1g - 10 ampulas'),
('Dra. Laura Costa', 'Losartana 50mg - 60 comprimidos'),
('Dr. Pedro Santos', 'Simvastatina 20mg - 30 comprimidos'),
('Dra. Fernanda Lima', 'Metformina 850mg - 90 comprimidos'),
('Dr. Rafael Pereira', 'Omeprazol 20mg - 28 cápsulas'),
('Dra. Beatriz Martins', 'Cloridrato de Sertralina 50mg - 30 comprimidos'),
('Dr. Gustavo Almeida', 'Cetoconazol 200mg - 14 comprimidos'),
('Dra. Juliana Freitas', 'Cetoprofeno 100mg - 20 cápsulas'),
('Dr. Luís Oliveira', 'Furosemida 40mg - 30 comprimidos'),
('Dra. Camila Costa', 'Prednisona 20mg - 15 comprimidos'),
('Dr. Marcos Silva', 'Hydroxicloroquina 200mg - 30 comprimidos'),
('Dra. Isabel Santos', 'Metoclopramida 10mg - 20 comprimidos'),
('Dr. Felipe Souza', 'Cloridrato de Propranolol 40mg - 30 comprimidos'),
('Dra. Paula Lima', 'Gliclazida 80mg - 60 comprimidos'),
('Dr. André Pereira', 'Ranitidina 150mg - 28 comprimidos'),
('Dra. Tatiane Martins', 'Azitromicina 500mg - 6 comprimidos'),
('Dr. Leonardo Costa', 'Loratadina 10mg - 20 comprimidos'),
('Dra. Renata Almeida', 'Enalapril 10mg - 30 comprimidos'),
('Dr. Ricardo Oliveira', 'Diazepam 10mg - 20 comprimidos'),
('Dra. Bruna Santos', 'Valeriana 100mg - 30 cápsulas'),
('Dr. Eduardo Freitas', 'Captopril 25mg - 60 comprimidos'),
('Dra. Mariana Silva', 'Naproxeno 500mg - 30 comprimidos'),
('Dr. Alexandre Lima', 'Levotiroxina 50mcg - 30 comprimidos'),
('Dra. Juliana Oliveira', 'Buspirona 10mg - 20 comprimidos'),
('Dr. Sérgio Costa', 'Doxiciclina 100mg - 14 comprimidos'),
('Dra. Luciana Santos', 'Amlodipina 5mg - 30 comprimidos'),
('Dr. Gustavo Freitas', 'Cloridrato de Venlafaxina 75mg - 30 cápsulas'),
('Dra. Natalia Almeida', 'Clofibrato 500mg - 20 comprimidos'),
('Dr. Henrique Silva', 'Metadona 10mg - 10 comprimidos'),
('Dra. Mariana Costa', 'Ribavirina 200mg - 28 cápsulas'),
('Dr. Gabriel Lima', 'Ciprofloxacino 500mg - 14 comprimidos'),
('Dra. Larissa Santos', 'Cloridrato de Cloridato de Trazodona 50mg - 30 comprimidos'),
('Dr. Vitor Almeida', 'Propranolol 40mg - 30 comprimidos'),
('Dra. Simone Oliveira', 'Fexofenadina 180mg - 10 comprimidos'),
('Dr. Caio Costa', 'Fenitoína 100mg - 30 comprimidos'),
('Dra. Andréa Silva', 'Sibutramina 15mg - 30 cápsulas'),
('Dr. Rafael Martins', 'Zolpidem 10mg - 20 comprimidos'),
('Dr. Ricardo Lima', 'Metronidazol 500mg - 20 comprimidos'),
('Dra. Aline Costa', 'Dextrometorfano 30mg - 15 xícaras'),
('Dr. Samuel Pereira', 'Cloridrato de Ranitidina 150mg - 30 comprimidos'),
('Dra. Júlia Martins', 'Lorazepam 2mg - 20 comprimidos'),
('Dr. Fernando Silva', 'Sulfato de Hidroxicloroquina 200mg - 20 comprimidos'),
('Dra. Carolina Lima', 'Ciproterona 50mg - 28 comprimidos'),
('Dr. Alexandre Ribeiro', 'Glipizida 5mg - 30 comprimidos'),
('Dra. Luciana Freitas', 'Propafenona 150mg - 20 comprimidos'),
('Dr. Pedro Martins', 'Colchicina 0,5mg - 10 comprimidos'),
('Dra. Roberta Oliveira', 'Piroxicam 20mg - 30 cápsulas');