USE projetoIntegradorTelemedicina;

INSERT INTO Prescricao (medicamento, observacao, ID_PACIENTE, ID_MEDICO) VALUES
('Paracetamol', 'Tomar 1 comprimido de 500mg a cada 8 horas por 5 dias', 35, 12),
('Amoxicilina', 'Tomar 1 comprimido de 1g a cada 12 horas por 7 dias', 7, 24),
('Ibuprofeno', 'Tomar 2 comprimidos de 200mg a cada 6 horas por 3 dias', 22, 50),
('Losartana', 'Tomar 1 comprimido de 50mg uma vez ao dia', 45, 31),
('Omeprazol', 'Tomar 1 cápsula de 20mg em jejum por 10 dias', 9, 18),
('Azitromicina', 'Tomar 1 comprimido de 500mg uma vez ao dia por 3 dias', 29, 6),
('Simvastatina', 'Tomar 1 comprimido de 40mg à noite', 4, 42),
('Metformina', 'Tomar 1 comprimido de 850mg duas vezes ao dia', 12, 36),
('Clonazepam', 'Tomar 1 comprimido de 2mg antes de dormir', 50, 3),
('Cetirizina', 'Tomar 1 comprimido de 10mg uma vez ao dia', 17, 28),
('Dipirona', 'Tomar 40 gotas a cada 6 horas por 3 dias', 10, 23),
('Loratadina', 'Tomar 1 comprimido de 10mg uma vez ao dia', 18, 41),
('Cefalexina', 'Tomar 1 comprimido de 500mg a cada 6 horas por 7 dias', 3, 14),
('Prednisona', 'Tomar 1 comprimido de 20mg uma vez ao dia por 5 dias', 25, 32),
('Ranitidina', 'Tomar 1 comprimido de 150mg duas vezes ao dia por 14 dias', 11, 8),
('Hidroxicloroquina', 'Tomar 2 comprimidos de 200mg uma vez ao dia', 36, 5),
('Furosemida', 'Tomar 1 comprimido de 40mg uma vez ao dia', 40, 27),
('Levotiroxina', 'Tomar 1 comprimido de 100mcg em jejum todos os dias', 6, 13),
('Fluconazol', 'Tomar 1 cápsula de 150mg em dose única', 21, 37),
('Tramadol', 'Tomar 1 comprimido de 50mg a cada 8 horas se necessário', 2, 16),
('Atenolol', 'Tomar 1 comprimido de 50mg uma vez ao dia', 16, 9),
('Captopril', 'Tomar 1 comprimido de 25mg a cada 12 horas', 28, 35),
('Dexametasona', 'Tomar 1 comprimido de 4mg uma vez ao dia por 5 dias', 47, 44),
('Carbamazepina', 'Tomar 1 comprimido de 200mg a cada 12 horas', 8, 33),
('Bromoprida', 'Tomar 30 gotas a cada 8 horas antes das refeições', 14, 22),
('Cloridrato de Sertralina', 'Tomar 1 comprimido de 50mg uma vez ao dia pela manhã', 33, 11),
('Diclofenaco', 'Tomar 1 comprimido de 50mg a cada 8 horas por 5 dias', 19, 25),
('Clindamicina', 'Tomar 1 cápsula de 300mg a cada 6 horas por 7 dias', 41, 30),
('Fenitoína', 'Tomar 1 comprimido de 100mg a cada 8 horas', 27, 20),
('Omeprazol', 'Tomar 1 cápsula de 20mg em jejum todos os dias', 13, 4),
('Cetoprofeno', 'Tomar 1 comprimido de 150mg uma vez ao dia por 5 dias', 5, 26),
('Lorazepam', 'Tomar 1 comprimido de 1mg antes de dormir', 34, 15),
('Amiodarona', 'Tomar 1 comprimido de 200mg uma vez ao dia', 43, 29),
('Alprazolam', 'Tomar 1 comprimido de 0.5mg duas vezes ao dia', 31, 48),
('Clonidina', 'Tomar 1 comprimido de 100mcg duas vezes ao dia', 26, 19),
('Propranolol', 'Tomar 1 comprimido de 40mg duas vezes ao dia', 20, 46),
('Aspirina', 'Tomar 1 comprimido de 100mg uma vez ao dia', 48, 21),
('Escitalopram', 'Tomar 1 comprimido de 10mg uma vez ao dia', 30, 17),
('Levomepromazina', 'Tomar 1 comprimido de 25mg antes de dormir', 49, 39),
('Metoprolol', 'Tomar 1 comprimido de 50mg uma vez ao dia', 15, 7),
('Benzilpenicilina', 'Tomar 1 injeção de 1.200.000 UI a cada 24 horas por 5 dias', 37, 11),
('Glibenclamida', 'Tomar 1 comprimido de 5mg duas vezes ao dia', 24, 43),
('Meloxicam', 'Tomar 1 comprimido de 15mg uma vez ao dia por 7 dias', 32, 16),
('Prednisolona', 'Tomar 1 comprimido de 20mg uma vez ao dia por 10 dias', 38, 34),
('Lidocaína', 'Aplicar 1 ampola de 2% como anestésico local', 42, 45),
('Amlodipino', 'Tomar 1 comprimido de 5mg uma vez ao dia', 1, 20),
('Ivermectina', 'Tomar 2 comprimidos de 6mg em dose única', 50, 13),
('Enalapril', 'Tomar 1 comprimido de 10mg duas vezes ao dia', 23, 36),
('Doxiciclina', 'Tomar 1 comprimido de 100mg a cada 12 horas por 7 dias', 46, 5),
('Rivastigmina', 'Tomar 1 cápsula de 6mg duas vezes ao dia', 39, 9);

SELECT * FROM Prescricao;