/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.telemedicina.subtelas;

import br.com.telemedicina.bd.BD;
import br.com.telemedicina.repository.BoletoPDF;
import br.com.telemedicina.repository.PacienteRepository;
import br.com.telemedicina.repository.TipoAtendimentoRepository;
import br.com.telemedicina.utils.LimitaCaracter;
import java.sql.*;
import javax.swing.*;
import java.awt.image.BufferedImage;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import java.util.UUID;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
/**
 *
 * @author Talisson53899806
 */
public class Pagamento extends javax.swing.JDialog {

    private float valorPagamento;
    
    /**
     * Creates new form pagamento
     */
    public Pagamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void setInformacoesPagamento(float valor) {
        this.valorPagamento = valor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pixRadioButton = new javax.swing.JRadioButton();
        cartaoDRadioButton = new javax.swing.JRadioButton();
        cartaoCRadioButton = new javax.swing.JRadioButton();
        boletoRadioButton = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelNf = new javax.swing.JLabel();
        labelCodigoPagamento = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        campoNumeroCartaoCredito = new javax.swing.JTextField();
        campoNomeCredito = new javax.swing.JTextField();
        campoCvvCredito = new javax.swing.JFormattedTextField();
        nomeCreditoLabel = new javax.swing.JLabel();
        vencimentoCreditoLabel = new javax.swing.JLabel();
        cvvCreditoLabel = new javax.swing.JLabel();
        numeroCreditoLabel = new javax.swing.JLabel();
        campoVencimentoCredito = new javax.swing.JFormattedTextField();
        numeroParcelasCredito = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        imagemBandeira = new javax.swing.JLabel();
        escolhaNumeroParcelas = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        nomeDebitoLabel = new javax.swing.JLabel();
        campoNomeDebito = new javax.swing.JTextField();
        campoNumeroCartaoDebito = new javax.swing.JTextField();
        numeroDebitoLabel = new javax.swing.JLabel();
        vencimentoDebitoLabel = new javax.swing.JLabel();
        campoVencimentoDebito = new javax.swing.JFormattedTextField();
        campoCvvDebito = new javax.swing.JFormattedTextField();
        cvvDebitoLabel = new javax.swing.JLabel();
        tituloDebitoLabel = new javax.swing.JLabel();
        imagemBandeira1 = new javax.swing.JLabel();
        botaoPagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jSplitPane1.setDividerLocation(351);
        jSplitPane1.setDividerSize(0);

        jPanel1.setBackground(new java.awt.Color(46, 169, 248));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Pagamento");

        pixRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(pixRadioButton);
        pixRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pixRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        pixRadioButton.setText("Pix");
        pixRadioButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cartaoDRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(cartaoDRadioButton);
        cartaoDRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cartaoDRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        cartaoDRadioButton.setText("Cartão de Débito");
        cartaoDRadioButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cartaoDRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartaoDRadioButtonMouseClicked(evt);
            }
        });
        cartaoDRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaoDRadioButtonActionPerformed(evt);
            }
        });

        cartaoCRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(cartaoCRadioButton);
        cartaoCRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cartaoCRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        cartaoCRadioButton.setText("Cartão de Credito");
        cartaoCRadioButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cartaoCRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartaoCRadioButtonMouseClicked(evt);
            }
        });

        boletoRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(boletoRadioButton);
        boletoRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boletoRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        boletoRadioButton.setText("Boleto");
        boletoRadioButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boletoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boletoRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(pixRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(cartaoDRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(cartaoCRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(boletoRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(82, 82, 82)
                .addComponent(pixRadioButton)
                .addGap(34, 34, 34)
                .addComponent(cartaoDRadioButton)
                .addGap(35, 35, 35)
                .addComponent(cartaoCRadioButton)
                .addGap(35, 35, 35)
                .addComponent(boletoRadioButton)
                .addContainerGap(345, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Resumo da Compra/Serviço");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("NF:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Código do pagamento:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Valor:");

        labelNf.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelNf.setForeground(new java.awt.Color(0, 204, 0));

        labelCodigoPagamento.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelCodigoPagamento.setForeground(new java.awt.Color(0, 204, 0));

        labelValor.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelValor.setForeground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelNf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelCodigoPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(labelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNf, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCodigoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        campoNumeroCartaoCredito.setDocument(new LimitaCaracter(19));
        campoNumeroCartaoCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroCartaoCreditoActionPerformed(evt);
            }
        });

        try {
            campoCvvCredito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCvvCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCvvCreditoActionPerformed(evt);
            }
        });

        nomeCreditoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nomeCreditoLabel.setForeground(new java.awt.Color(0, 0, 0));
        nomeCreditoLabel.setText("NOME COMPLETO");

        vencimentoCreditoLabel.setBackground(new java.awt.Color(0, 0, 0));
        vencimentoCreditoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vencimentoCreditoLabel.setForeground(new java.awt.Color(0, 0, 0));
        vencimentoCreditoLabel.setText("VENCIMENTO");

        cvvCreditoLabel.setBackground(new java.awt.Color(0, 0, 0));
        cvvCreditoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cvvCreditoLabel.setForeground(new java.awt.Color(0, 0, 0));
        cvvCreditoLabel.setText("CVV");

        numeroCreditoLabel.setBackground(new java.awt.Color(0, 0, 0));
        numeroCreditoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        numeroCreditoLabel.setForeground(new java.awt.Color(0, 0, 0));
        numeroCreditoLabel.setText("N° DO CARTÃO");

        try {
            campoVencimentoCredito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        numeroParcelasCredito.setBackground(new java.awt.Color(0, 0, 0));
        numeroParcelasCredito.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        numeroParcelasCredito.setForeground(new java.awt.Color(0, 0, 0));
        numeroParcelasCredito.setText("N° DE PARCELAS");

        tituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(0, 0, 0));
        tituloLabel.setText("CARTÃO DE CRÉDITO");

        errorLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 0, 0));

        escolhaNumeroParcelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "1x", "2x", "3x", "4x", "5x", "6x", "7x", "8x", "9x", "10x", "11x", "12x" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(tituloLabel)
                .addGap(28, 28, 28))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(errorLabel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nomeCreditoLabel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(numeroCreditoLabel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(vencimentoCreditoLabel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(campoVencimentoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoNomeCredito, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(campoNumeroCartaoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(imagemBandeira)))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cvvCreditoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numeroParcelasCredito)
                        .addGap(108, 108, 108))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(campoCvvCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(escolhaNumeroParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(tituloLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLabel)
                .addGap(55, 55, 55)
                .addComponent(nomeCreditoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNomeCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(numeroCreditoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoNumeroCartaoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(imagemBandeira)
                        .addGap(8, 8, 8)))
                .addGap(18, 18, 18)
                .addComponent(vencimentoCreditoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoVencimentoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cvvCreditoLabel)
                    .addComponent(numeroParcelasCredito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCvvCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(escolhaNumeroParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crédito", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        nomeDebitoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nomeDebitoLabel.setForeground(new java.awt.Color(0, 0, 0));
        nomeDebitoLabel.setText("NOME COMPLETO");

        campoNumeroCartaoDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroCartaoDebitoActionPerformed(evt);
            }
        });

        numeroDebitoLabel.setBackground(new java.awt.Color(0, 0, 0));
        numeroDebitoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        numeroDebitoLabel.setForeground(new java.awt.Color(0, 0, 0));
        numeroDebitoLabel.setText("N° DO CARTÃO");

        vencimentoDebitoLabel.setBackground(new java.awt.Color(0, 0, 0));
        vencimentoDebitoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vencimentoDebitoLabel.setForeground(new java.awt.Color(0, 0, 0));
        vencimentoDebitoLabel.setText("VENCIMENTO");

        try {
            campoVencimentoDebito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            campoCvvDebito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCvvDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCvvDebitoActionPerformed(evt);
            }
        });

        cvvDebitoLabel.setBackground(new java.awt.Color(0, 0, 0));
        cvvDebitoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cvvDebitoLabel.setForeground(new java.awt.Color(0, 0, 0));
        cvvDebitoLabel.setText("CVV");

        tituloDebitoLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tituloDebitoLabel.setForeground(new java.awt.Color(0, 0, 0));
        tituloDebitoLabel.setText("CARTÃO DE DÉBITO");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(tituloDebitoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(campoNumeroCartaoDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(imagemBandeira1)
                                .addGap(90, 90, 90))
                            .addComponent(campoNomeDebito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeDebitoLabel)
                            .addComponent(numeroDebitoLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cvvDebitoLabel)
                            .addComponent(campoCvvDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vencimentoDebitoLabel)
                                .addGap(120, 120, 120))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(campoVencimentoDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloDebitoLabel)
                .addGap(35, 35, 35)
                .addComponent(nomeDebitoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNomeDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(numeroDebitoLabel)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(imagemBandeira1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNumeroCartaoDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cvvDebitoLabel)
                    .addComponent(vencimentoDebitoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCvvDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoVencimentoDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Débito", jPanel5);

        botaoPagar.setBackground(new java.awt.Color(0, 153, 0));
        botaoPagar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        botaoPagar.setForeground(new java.awt.Color(0, 0, 0));
        botaoPagar.setText("Pagar");
        botaoPagar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(354, 354, 354))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(botaoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Nota Fiscal
        int rand_int1;
        StringBuilder allNumbers = new StringBuilder(); // Usar StringBuilder para eficiência na concatenação
        for (int i = 1; i <= 15; i++) {
            Random rand = new Random();
            rand_int1 = rand.nextInt(1000) + 1; // Gera número entre 1 e 1000

            // Concatena o número ao StringBuilder com um espaço para separação
            allNumbers.append(rand_int1);
        }
        this.labelNf.setText(allNumbers.toString());
        
        //Codigo de Pagamento
        int rand_int2;
        StringBuilder alNumbers = new StringBuilder(); // Usar StringBuilder para eficiência na concatenação
        
        for (int i = 1; i <= 15; i++) {
            Random rand = new Random();
            rand_int2 = rand.nextInt(1000) + 1; // Gera número entre 1 e 1000
            
            // Concatena o número ao StringBuilder com um espaço para separação
            alNumbers.append(rand_int2);
        }
        this.labelCodigoPagamento.setText(alNumbers.toString());

        
        this.labelValor.setText(String.valueOf(valorPagamento));
        
        this.jTabbedPane1.removeAll();
    }//GEN-LAST:event_formWindowOpened

    private void cartaoDRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaoDRadioButtonMouseClicked
        if (this.jTabbedPane1.getTabCount() > 0) {
            this.jTabbedPane1.removeAll();
        }
        
        this.jTabbedPane1.addTab("Débito", jPanel5);
    }//GEN-LAST:event_cartaoDRadioButtonMouseClicked

    private void cartaoCRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaoCRadioButtonMouseClicked
        if (this.jTabbedPane1.getTabCount() > 0) {
            this.jTabbedPane1.removeAll();
        }
        
        this.jTabbedPane1.addTab("Crédito", jPanel4);
    }//GEN-LAST:event_cartaoCRadioButtonMouseClicked

    private void campoCvvCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCvvCreditoActionPerformed

    }//GEN-LAST:event_campoCvvCreditoActionPerformed

    private void botaoPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPagarActionPerformed
        //Valida a sua escolha
        if (!validaEscolha()) {
            return;
            
        }
        
        TipoAtendimentoRepository tatRepo = new TipoAtendimentoRepository();
        
        PacienteRepository        pacRepo = new PacienteRepository();
        
        
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("pagamento.txt"))) {
            
            //Captura as opções selecionadas
            boolean pix            = this.pixRadioButton.isSelected();
            boolean cartaoC        = this.cartaoCRadioButton.isSelected();
            boolean cartaoD        = this.cartaoDRadioButton.isSelected();
            boolean boleto         = this.boletoRadioButton.isSelected();
            String notaFiscal      = this.labelNf.getText();
            String codigoPagamento = this.labelCodigoPagamento.getText();
            String valor           = this.labelValor.getText();
            int idTipoAtendimento  = tatRepo.getIdByValor(valor);
            int idPaciente         = pacRepo.getIdByEmailArquivo();
            String nomePaciente    = pacRepo.getNomeByEmailArquivo();
            String cpfPaciente     = pacRepo.getCpfByEmailArquivo();
            String enderecoPac     = pacRepo.getEnderecoByEmailArquivo();
            
            //Conecta no Banco de Dados
            BD banco = new BD();
            banco.conectaBD();
            
            //Variáveis para os valores a serem inseridos no banco de dados
            String tipoPagamento = "";
            String pixCopiaCola = null;
            
            //Verifica a opção selecionada e executa a lógica correspondente
            if (pix) {
                tipoPagamento = "PIX";
                pixCopiaCola = gerarCodigoPix(); //Gerar código Copia e Cola
                
                //Exibe o código pix Copia e Cola no JOptionPane
                JOptionPane.showMessageDialog(this,
                        "O pix copia e cola foi gerado: \n" + pixCopiaCola + "\n",
                        "Pix Copia e Cola",
                        JOptionPane.OK_OPTION,
                        exibiQRCode(pixCopiaCola)); 
                
            } else if (boleto) {
                try {
                    tipoPagamento = "Boleto";
                    String filePath = System.getProperty("user.home") + "/Downloads/boleto.pdf";
                    BoletoPDF boletoPDF = new BoletoPDF();
                    boletoPDF.gerarBoleto(filePath, nomePaciente, cpfPaciente, enderecoPac, valor);
                    JOptionPane.showMessageDialog(this, "Boleto gerado com sucesso em: " + filePath);
                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Erro ao gerar o boleto: " + e.getMessage(),
                            "Erro",
                            JOptionPane.ERROR_MESSAGE);
                }
                
            } else if (cartaoC) {
                if (!validaCamposCartaoCredito()) {
                    return;
                }
                
                tipoPagamento = "Cartão de Crédito";
                JOptionPane.showMessageDialog(this,
                        "Pagamento via Cartão de Crédito selecionado!!");
                
            } else if (cartaoD) {
                if (!validaCamposCartaoDebito()) {
                    return;
                }
                
                tipoPagamento = "Cartão de Débito";
                JOptionPane.showMessageDialog(this,
                        "Pagamento via Cartão de Débito selecionado!!");
            }
            
            //Se algum tipo de pagamento foi selecionado, insere no banco de dados
            if (!tipoPagamento.isEmpty()) {
                //Cria a query de inserção
                String query = "INSERT INTO Pagamento (tipoPagamento, notaFiscal, codigoPagamento, ID_TipoAtendimento, ID_PACIENTE) VALUES (?,?,?,?,?)";
                PreparedStatement ps = banco.getPreparedStatement(query);
                
                //Define os parâmetros da query
                ps.setString(1, tipoPagamento);
                ps.setString(2, notaFiscal);
                ps.setString(3, codigoPagamento);
                ps.setInt(4, idTipoAtendimento);
                ps.setInt(5, idPaciente);
                
                //executa a query
                int rowsAffected = ps.executeUpdate();
                
                //Verifica se a inserção foi bem-sucedida
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this,
                            "Pagamento salvo com sucesso no banco de dados!!");
                    
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Erro ao salvar o pagamento!!");
                    
                }
                
            }
            
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Erro de conexão com o banco de dados: " + ex.getMessage());
           
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Erro ao salvar o arquivo de pagamento: " + ex.getMessage());
            
        }
        
        this.dispose();
    }//GEN-LAST:event_botaoPagarActionPerformed

    //Método para gerar o QR Code
    private BufferedImage gerarQRCode(String dados, int largura, int altura) {
        QRCodeWriter qrCodeWriter = new QRCodeWriter();
        BufferedImage imagemQRCode = null;
        
        try {
            BitMatrix bitMatrix = qrCodeWriter.encode(dados, BarcodeFormat.QR_CODE, largura,altura);
            imagemQRCode = MatrixToImageWriter.toBufferedImage(bitMatrix);
            
        } catch (WriterException e) {
            e.printStackTrace();
        }
        
        return imagemQRCode;
    }
    
    private ImageIcon exibiQRCode(String codigoPix) {
        //Gera o QR Code com 200x200 pixels
        BufferedImage qrCodeImage = gerarQRCode(codigoPix, 200, 200);
        
        //Converte a imagem em ImageIcon
        ImageIcon qrCodeIcon = new ImageIcon(qrCodeImage);
        
        return qrCodeIcon;
    }
    
    private boolean validaCamposCartaoDebito() {
        if ("".equals(this.campoNumeroCartaoDebito.getText()) ||
                "".equals(this.campoCvvDebito.getText()) ||
                "".equals(this.campoNomeDebito.getText()) ||
                "".equals(this.campoVencimentoDebito.getText())) {
            
            JOptionPane.showMessageDialog(this,
                    "Ainda há campos em branco!!");
            
            return false;
        }
        return true;
    }
    
    private boolean validaCamposCartaoCredito() {
        if ("".equals(this.campoNumeroCartaoCredito.getText()) ||
                "".equals(this.campoCvvCredito.getText()) ||
                "".equals(this.campoNomeCredito.getText()) ||
                "".equals(this.campoVencimentoCredito.getText())) {
            
            JOptionPane.showMessageDialog(this,
                    "Ainda há campos em branco!!");
            
            return false;
        }
        return true;
    }
    
    private void campoCvvDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCvvDebitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCvvDebitoActionPerformed
    
    private void campoNumeroCartaoCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeroCartaoCreditoActionPerformed
        String numeroCartao = campoNumeroCartaoCredito.getText();
        if(validarCartao(numeroCartao)) {
            identificarBandeira(numeroCartao);
        } else {
            errorLabel.setText("Número do cartão invalido.");
        }
    }//GEN-LAST:event_campoNumeroCartaoCreditoActionPerformed

    private void cartaoDRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaoDRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cartaoDRadioButtonActionPerformed

    private void boletoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boletoRadioButtonActionPerformed
        this.jTabbedPane1.removeAll();
    }//GEN-LAST:event_boletoRadioButtonActionPerformed

    private void campoNumeroCartaoDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeroCartaoDebitoActionPerformed
        String numeroCartao = campoNumeroCartaoDebito.getText();
        if(validarCartao(numeroCartao)) {
            identificarBandeira(numeroCartao);
        } else {
            errorLabel.setText("Número do cartão invalido.");
        }
    }//GEN-LAST:event_campoNumeroCartaoDebitoActionPerformed

    //validação do número do cartão usando o algoritmo luhn
    private static boolean validarCartao(String numeroCartao) {
        //Remover espaços em branco
        numeroCartao = numeroCartao.replaceAll("\\s+", "");
        
        //Verifica se o número do cartão é válido
        if (!numeroCartao.matches("\\d+")) {
            return false; //Número não é válido
        }
        
        int soma = 0;
        boolean alternar = false;
        
        //Vai ler a quantidade de dígitos que foi inserido e fazer a soma da trás pra frente
        for (int i = numeroCartao.length() - 1; i>=0; i--) {
            int digito = Character.getNumericValue(numeroCartao.charAt(i));
            
            //Verifica se o segundo dígito deve ser multiplicado
            if (alternar) {
                digito *= 2; //Se sim, ele duplica o dígito atual
                if (digito > 9) {
                    digito-= 9; //Se o dígito multiplicado for maior que 9, ele subtrai 9 deles equvalente a somar os dígitos restantes
                }
            }
            
            soma += digito;
            alternar = !alternar;
        }
        
        return soma % 10 == 0;
    }
    
    //Método para identificar a bandeira do cartão
    private String identificarBandeira(String numeroCartao) {
        String bandeira = "DESCONHECIDO"; //Valor Padrão
        String caminhoImagem = ""; //Caminho para a imagem da bandeira
        
        if (numeroCartao.startsWith("4")) {
            bandeira = "VISA";
            caminhoImagem = "src/main/resources/images/visa.png";
        } else if (numeroCartao.startsWith("5")) {
            bandeira = "MASTERCARD";
            caminhoImagem = "src/main/resources/images/mastercard.jpg";
        } else if (numeroCartao.startsWith("3")) {
            if (numeroCartao.length() == 15) {
                bandeira = "AMERICA EXPRESS";
                caminhoImagem = "src/main/resources/images/amex.jpeg";
            } else {
                bandeira = "DINERS CLUB";
                caminhoImagem = "src/main/resources/images/dinersClub.png";
            }
            
        } else if (numeroCartao.startsWith("6")) {
            bandeira = "DISCOVER";
            caminhoImagem = "src/main/resources/images/discover.png";
        } else if (numeroCartao.startsWith("37")) {
            bandeira = "AMERICAN EXPRESS";
            caminhoImagem = "src/main/resources/images/amex.jpeg";
        }
        
        //Verifica se o caminho da imagem não está vazio e define a imagem no label
        if (!caminhoImagem.isEmpty()) {
            ImageIcon iconeBandeira = new ImageIcon(caminhoImagem);
            imagemBandeira.setIcon(iconeBandeira);
            imagemBandeira1.setIcon(iconeBandeira);
        }
        
        return bandeira;
    }
    
    //Validação De Escolha
    private boolean validaEscolha() {
         // Verifica se algum dos RadioButtons foi selecionado
        if (!this.pixRadioButton.isSelected()     &&
            !this.cartaoCRadioButton.isSelected() &&
            !this.cartaoDRadioButton.isSelected() &&
            !this.boletoRadioButton.isSelected()   ) {
            // Mostra uma mensagem de erro se nenhuma opção foi selecionada
            JOptionPane.showMessageDialog(this,
                    "Escolha uma Opção!!!");
            return false;
        }
        // Retorna true se alguma opção foi selecionada
        return true;
    }
    
    //Gerador de Código Pix
    public static String gerarCodigoPix() {
        String codigoAleatorio = UUID.randomUUID().toString().replace("-", "").toUpperCase();
        
        String codigoPix = "00020126" + "0014BR.GOV.BCB.PIX0114" + "5531987654321" +
                           "5204000053039865404" + "20.005802BR5909Empresa6009SAO PAULO" +
                           "62070503***6304" + codigoAleatorio;
        
        return codigoPix;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pagamento dialog = new Pagamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton boletoRadioButton;
    private javax.swing.JButton botaoPagar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField campoCvvCredito;
    private javax.swing.JFormattedTextField campoCvvDebito;
    private javax.swing.JTextField campoNomeCredito;
    private javax.swing.JTextField campoNomeDebito;
    private javax.swing.JTextField campoNumeroCartaoCredito;
    private javax.swing.JTextField campoNumeroCartaoDebito;
    private javax.swing.JFormattedTextField campoVencimentoCredito;
    private javax.swing.JFormattedTextField campoVencimentoDebito;
    private javax.swing.JRadioButton cartaoCRadioButton;
    private javax.swing.JRadioButton cartaoDRadioButton;
    private javax.swing.JLabel cvvCreditoLabel;
    private javax.swing.JLabel cvvDebitoLabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JComboBox<String> escolhaNumeroParcelas;
    private javax.swing.JLabel imagemBandeira;
    private javax.swing.JLabel imagemBandeira1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelCodigoPagamento;
    private javax.swing.JLabel labelNf;
    private javax.swing.JLabel labelValor;
    private javax.swing.JLabel nomeCreditoLabel;
    private javax.swing.JLabel nomeDebitoLabel;
    private javax.swing.JLabel numeroCreditoLabel;
    private javax.swing.JLabel numeroDebitoLabel;
    private javax.swing.JLabel numeroParcelasCredito;
    private javax.swing.JRadioButton pixRadioButton;
    private javax.swing.JLabel tituloDebitoLabel;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JLabel vencimentoCreditoLabel;
    private javax.swing.JLabel vencimentoDebitoLabel;
    // End of variables declaration//GEN-END:variables
}
